- name: Tiffany Yeung
  tagline: front-end shitposter & honorary SE
  img: tiffanynwyeung.jpg
  links: 
    - website: tiffanynwyeung.com
    - github_username: tiffanynwyeung

- name: Mr. Goose
  tagline: honking UWaterloo mascot
